version: '3.4'
name: apiprodutorruralsensores
services:
  produtorruralsensores.api:
    image: ${DOCKER_REGISTRY-}produtorruralsensoresapi
    container_name: apiprodutorruralsensores
    build:
      context: .
      dockerfile: src/ProdutorRuralSensores.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5002:80"
    networks:
      - agro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agro-network:
    external: true